eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:11111/eureka

server:
  port: 18888
  context-path: /client

#spring.session.store-type=redis
#spring.datasource.jndi-name=jdbc/dataSource

spring:
  application:
    name: MOVINGDEMO-USERS
  datasource:
    url: jdbc:mysql://localhost:3306/hello
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  output:
    ansi:
      enabled: detect

security:
  password: password
  oauth2:
    resource:
      user-info-uri: http://localhost:8888/uaa/me

storage:
  rootLocation: c:\sj\upload\images
  
debug: true
logging:
  level:
    com.shijin.learn: trace
    org.springframework.security: info
    org.springframework.cloud.netflix.zuul: none
    com.netflix.zuul: none
    org.springframework.security.web.util: info
    org.springframework.web.servlet: info

